### PR TITLE
Add logging for Tyche

### PR DESCRIPTION
**Pull request by pppls**
I wrote a start on how to implement tyche logging. I am aware that I should also change the various overloads for Sample (and for SampleAsync, etc.
) and the various other test approaches but thought it would be better to get some confirmation that current approach is okay before I would make similar changes elsewhere.

### CODE REVIEW

**Comment by AnthonyLloyd** [comment]
I think this can be added as a `Sample` overload that takes a `Action<T, bool> logger` in a similar way to Classifier (will need to add a catch around assert for exception failures etc). That way we can keep this out of the core code and more opt in.

I think it could be really good. Do you write to a file as it is logging to get realtime stats?

If you do this end to end for one overload (the first `Action<T>` assert one) I can make sure it covers all the others (ModelBased, Faster possibly  if it generalises).

```csharp
public static void Sample<T>(this Gen<T> gen, Func<T, string> classify, Action<string> writeLine,
    string? seed = null, long iter = -1, int time = -1, int threads = -1, Func<T, string>? print = null)
{
    var classifier = new Classifier();
    Sample(gen, t =>
    {
        var time = Stopwatch.GetTimestamp();
        var name = classify(t);
        classifier.Add(name, Stopwatch.GetTimestamp() - time);
    }, null, seed, iter, time, threads, print);
    classifier.Print(writeLine);
}
```

**Comment by pppls** [comment]
Currently it first records all results and then logs so not real-time, but I think that's a simple change. I'll put all the logging/Tyche stuff in a separate file. 

> Actually adding an optional logger parameter to each method and switching the assert for a logged Action<T> much like the other optional parameters is the better way to go if we want to be able to set env vars. Reduces the number of overloads, keeps it consistent and is still opt in.

Ah right, we can just wrap the old assert function in a new function and assign it again to create a new assert.

One thing I am not sure about though is committing to Action<T,bool> as parameter input. What if we want to log some new information in the future that can only be obtained in SampleActionWorker? That would require another overload in Sample with yet another Action definition, otherwise it is not backwards compatible.

I think it is probably to use something like
```
public class LogContext<T>
{
    public T Value { get; set; }
    public bool Success { get; set; }
    // Additional fields can be added here in the future
}
```
as input parameter. However this does mean you cannot use the previous assert trick as it is.

**Comment by pppls** [comment]
@AnthonyLloyd I did some more work on this. I use a Channel (with the workers as producers and a writer as consumer) and a background thread such that writing to a file occurs in real-time. It is difficult to check if this works however - the vs code tyche plugin does not seem to automatically open upon generation of the data as it is supposed to do (at least, in Hypothesis). You can open the generated file manually of course but then it doesn't affirm that data is real-time visible.

There is one failing test - Pow10_Double from the Hashtests. It is not quite clear to me why.

Generated collections are a bit annoying to test because the tyche plugin expects a slightly different format from regular json, so deserialization is a bit annoying.

Finally, I find it a bit weird that duplicates are visible in tyche: 
image
image

I was under the impression that 
```                       
if (MinSize is null || Size.IsLessThan(size, MinSize))
                        {
                            assert(t);
                        }
                        else
                            skippedLocal++;
```
would skip it. At first I thought it was because of the try catch in the loggingAssert:
```
            assertWithLogging = t =>
            {
                try
                {
                    assert(t);
                    channel.Writer.TryWrite(new GenLogger.LogContext<T>(t, true));
                }
                catch
                {
                    channel.Writer.TryWrite(new GenLogger.LogContext<T>(t, true));
                    throw;
                }
            };
```
But removing the try catch entirely (meaning that there would not be written to the channel in case of exception) did not cause elements to be unique.

@Zac-HD is the automatic generation part of the vs code tyche plugin or of hypothesis?

**Comment by Zac-HD** [comment]
> is the automatic generation part of the vs code tyche plugin or of hypothesis?

Hypothesis is responsible for (incrementally) writing the `.jsonl` file, and [the Tyche VSCode plugin](https://marketplace.visualstudio.com/items?itemName=HarrisonGoldstein.tyche) is responsible for reading and displaying those results.

I think you're asking "why doesn't the GUI automatically open"; as far as I know this is just because Tyche knows about the default location of Hypothesis' `.jsonl` files but not about your implementation.  You can run the vscode `Tyche: Open` command and point it to the new location, and I *think* that will then be watched for further updates.  

Once you finalize this PR, we can also ask @hgoldstein95 to teach Tyche about the new location 🙂

**Comment by hgoldstein95** [comment]
Yes, I'd be happy to set the new directory as a default in Tyche! For now, you can configure Tyche to know about your output directory in the extension settings.

**Pull request merged**
